"""Add claimed by to gifts table

Revision ID: 255f07184205
Revises: 65477475eba1
Create Date: 2025-09-09 12:38:27.035834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255f07184205'
down_revision: Union[str, Sequence[str], None] = '65477475eba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('claimed', sa.Boolean(), nullable=True))
    op.add_column('gifts', sa.Column('claimed_by', sa.String(length=150), nullable=True))
    op.create_foreign_key(None, 'gifts', 'users', ['claimed_by'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gifts', type_='foreignkey')
    op.drop_column('gifts', 'claimed_by')
    op.drop_column('gifts', 'claimed')
    # ### end Alembic commands ###
