"""Add claimed by to gifts tables

Revision ID: 25e998e10f87
Revises: 96764cfd3e3f
Create Date: 2025-09-09 12:52:00.556524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25e998e10f87'
down_revision: Union[str, Sequence[str], None] = '96764cfd3e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('gifts_ibfk_2'), 'gifts', type_='foreignkey')
    op.drop_column('gifts', 'claimed_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('claimed_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('gifts_ibfk_2'), 'gifts', 'users', ['claimed_by'], ['id'])
    # ### end Alembic commands ###
