"""Add claimed by to gifts tables

Revision ID: 630f8abda40c
Revises: 255f07184205
Create Date: 2025-09-09 12:41:57.867021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '630f8abda40c'
down_revision: Union[str, Sequence[str], None] = '255f07184205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gifts', 'claimed_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('claimed_by', mysql.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
