"""Updated user table

Revision ID: 65afef8a298d
Revises: 81c3302ec9fd
Create Date: 2025-10-27 15:37:31.850339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65afef8a298d'
down_revision: Union[str, Sequence[str], None] = '81c3302ec9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.Enum('local', 'google', 'guest', 'user', name='authprovider'), nullable=False))
    op.add_column('users', sa.Column('mode', sa.Enum('local', 'google', 'guest', 'user', name='authprovider'), nullable=False))
    op.add_column('users', sa.Column('provider_id', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'mode')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
