"""Add hashed password column to users table

Revision ID: 81c3302ec9fd
Revises: 8b29e98ebe65
Create Date: 2025-10-13 17:38:22.721593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c3302ec9fd'
down_revision: Union[str, Sequence[str], None] = '8b29e98ebe65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('link', sa.String(length=500), nullable=False))
    op.add_column('gifts', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('gifts', sa.Column('note', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gifts', 'note')
    op.drop_column('gifts', 'price')
    op.drop_column('gifts', 'link')
    # ### end Alembic commands ###
