"""Add claimed  to gifts tables

Revision ID: 96764cfd3e3f
Revises: 630f8abda40c
Create Date: 2025-09-09 12:42:45.812905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96764cfd3e3f'
down_revision: Union[str, Sequence[str], None] = '630f8abda40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('claimed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gifts', 'users', ['claimed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gifts', type_='foreignkey')
    op.drop_column('gifts', 'claimed_by')
    # ### end Alembic commands ###
